# Generated by Django 5.0.2 on 2025-02-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('grade', models.CharField(choices=[('B1', '学部1年'), ('B2', '学部2年'), ('B3', '学部3年'), ('B4', '学部4年'), ('M1', '修士1年'), ('M2', '修士2年'), ('D1', '博士1年'), ('D2', '博士2年'), ('D3', '博士3年')], max_length=2, verbose_name='学年')),
                ('major', models.CharField(max_length=100, verbose_name='所属専攻')),
                ('weight', models.IntegerField(verbose_name='体重(kg)')),
                ('motto', models.CharField(max_length=200, verbose_name='座右の銘')),
                ('message', models.TextField(verbose_name='新入生に一言')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_photos/%Y/%m/', verbose_name='写真')),
                ('is_active', models.BooleanField(default=True, verbose_name='現役部員')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '部員',
                'verbose_name_plural': '部員',
                'ordering': ['grade', 'name'],
            },
        ),
    ]
